Forbedring run terraform
kartverket/github-workflows pull request #44
Opened 2022-12-19 13:20 UTC by EbiJon

The developers are allowed now to write the branch name without the full path. 
Example: (master) instead of (refs/heads/master).
OPS To Ensure backwards compatibility both branch name and full path are accepted.

2022-12-19 13:27 UTC, anderssonw requested changes

2022-12-19 13:27 UTC, anderssonw commented on .github/workflows/run-terraform.yml
> +        run: echo "$GITHUB_CONTEXT"
husk å fjerne denne

2022-12-19 13:27 UTC, anderssonw commented on .github/workflows/run-terraform.yml
> +        run: echo "$GITHUB_CONTEXT"
og denne

2022-12-19 13:29 UTC, anderssonw commented
husk også å bruke squash and merge på denne, mye teste-commits :P

2022-12-20 08:37 UTC, anderssonw approved these changes

2022-12-20 08:37 UTC, anderssonw commented on .github/workflows/run-terraform.yml
> +
denne og

2022-12-20 11:47 UTC, berg-thom approved these changes

2022-12-20 13:27 UTC, merged